export type GmCommandConfidence = "verificado" | "comun" | "variante";

export type GmCommandCategory =
  | "Inventario"
  | "Spawn"
  | "Movimiento"
  | "Moderacion"
  | "Comunicacion"
  | "Personaje"
  | "Misiones"
  | "Depuracion"
  | "Servidor"
  | "Red/Grupo";

export type GmCommand = {
  command: string;
  title: string;
  category: GmCommandCategory;
  syntax: string;
  example: string;
  description: string;
  notes: string;
  risk: "Bajo" | "Medio" | "Alto" | "Critico";
  prefix: "&" | "@@";
  server: "GameServer 1.36/1.38" | "GroupServer 1.38" | "Variante comunitaria";
  confidence: GmCommandConfidence;
};

type GmCommandSeed = Omit<GmCommand, "prefix" | "server" | "confidence"> & {
  confidence?: GmCommandConfidence;
};

const game = (command: GmCommandSeed): GmCommand => ({
  prefix: "&",
  server: "GameServer 1.36/1.38",
  confidence: "verificado",
  ...command,
});

const group = (command: GmCommandSeed): GmCommand => ({
  prefix: "@@",
  server: "GroupServer 1.38",
  confidence: "verificado",
  ...command,
});

const variant = (command: GmCommandSeed & { prefix: "&" | "@@" }): GmCommand => ({
  server: "Variante comunitaria",
  confidence: "variante",
  ...command,
});

export const gmCommandSources = [
  {
    label: "PKOdev editgmcmd",
    href: "https://github.com/V3ct0r1024/pkodev.tool.editgmcmd",
    detail: "Herramienta publica para editar/renombrar comandos GM en GameServer.exe (&) y GroupServer.exe (@@) de Tales of Pirates.",
  },
  {
    label: "Base de comandos editgmcmd",
    href: "https://github.com/V3ct0r1024/pkodev.tool.editgmcmd/blob/master/db/pkodev.tool.editgmcmd.json",
    detail: "Base usada para enumerar nombres de comandos presentes en GameServer 1.36/1.38 y GroupServer 1.38.",
  },
  {
    label: "PKOdev foro",
    href: "https://pkodev.com/forums/questions-help.7/",
    detail: "Comunidad tecnica TOP/PKO; las builds privadas suelen cambiar parametros, alias y permisos.",
  },
  {
    label: "Pirate King Online reglas",
    href: "https://piratekings.online/help/rules/",
    detail: "Referencia publica sobre operacion GM/moderacion en un servidor PKO actual.",
  },
];

export const gmJobAttributes = [
  { id: 1, label: "Swordsman" },
  { id: 2, label: "Hunter" },
  { id: 4, label: "Explorer" },
  { id: 5, label: "Herbalist" },
  { id: 8, label: "Champion" },
  { id: 9, label: "Crusader" },
  { id: 12, label: "Sharpshooter" },
  { id: 13, label: "Cleric" },
  { id: 14, label: "Seal Master" },
  { id: 16, label: "Voyager" },
];

export const gmCharacterAttributes = [
  { id: 0, label: "Nivel", warning: true },
  { id: 4, label: "Trabajo/clase", warning: true },
  { id: 5, label: "Reputacion" },
  { id: 6, label: "Puntos de atributos" },
  { id: 7, label: "Puntos de skill" },
  { id: 8, label: "Oro", warning: true },
  { id: 11, label: "SLV" },
  { id: 12, label: "Nivel de life-skill" },
  { id: 13, label: "Puntos de life-skill" },
  { id: 19, label: "Sail EXP" },
  { id: 50, label: "STR" },
  { id: 51, label: "ACC/AGI (la guia compartida se contradice)", warning: true },
  { id: 52, label: "AGI/ACC (la guia compartida se contradice)", warning: true },
  { id: 53, label: "CON" },
  { id: 54, label: "SPR" },
  { id: 69, label: "Velocidad de movimiento", warning: true },
  { id: 96, label: "Strength derivada", warning: true },
  { id: 97, label: "Agility derivada", warning: true },
  { id: 98, label: "Accuracy derivada", warning: true },
  { id: 99, label: "Constitution derivada", warning: true },
  { id: 100, label: "Spirit derivada", warning: true },
  { id: 102, label: "Velocidad de ataque", warning: true },
  { id: 104, label: "Ataque minimo", warning: true },
  { id: 105, label: "Ataque maximo", warning: true },
  { id: 106, label: "Defensa", warning: true },
  { id: 107, label: "HP maximo", warning: true },
  { id: 108, label: "SP maximo", warning: true },
  { id: 109, label: "Dodge", warning: true },
  { id: 110, label: "Hit rate", warning: true },
];

export const gmPetAttributes = [
  { id: 26, label: "Strength" },
  { id: 27, label: "Agility" },
  { id: 28, label: "Accuracy" },
  { id: 29, label: "Constitution" },
  { id: 30, label: "Spirit" },
];

export const gmCommandRecipes = [
  {
    title: "Cambiar nivel de otro personaje",
    steps: ['&qcha "Nekko"', "&attr 0,120,1503"],
    note: "Sustituye 1503 por el ID interno mostrado por qcha.",
  },
  {
    title: "Cambiar trabajo/clase",
    steps: ["&attr 4,9", "&attr 4,9,1503"],
    note: "El primer ejemplo aplica al contexto actual; el segundo usa character_id. 9 corresponde a Crusader.",
  },
  {
    title: "Agregar stat base",
    steps: ["&attr 50,100"],
    note: "Agrega/establece STR segun el comportamiento de tu build. Prueba primero con una cuenta de QA.",
  },
  {
    title: "Crear item simple o con gema",
    steps: ["&make 1,1", "&make 885,3,109"],
    note: "La codificacion gem_config puede cambiar por build. Valida el item antes de entregarlo.",
  },
  {
    title: "Subir stat de pet",
    steps: ["&itemattr 2,1,26,100"],
    note: "26 corresponde a Strength. Usa valores moderados.",
  },
  {
    title: "Moverse y traer jugador",
    steps: ["&move 200,200,garner", "&goto Nekko", "&call Nekko"],
    note: "move usa coordenadas/mapa, goto va hacia el personaje y call trae al personaje.",
  },
];

export const gmCommands: GmCommand[] = [
  game({
    command: "&move",
    title: "Moverse a coordenadas",
    category: "Movimiento",
    syntax: "&move <x>,<y>,<mapa>",
    example: "&move 200,200,garner",
    description: "Teletransporta al GM a coordenadas concretas dentro de un mapa.",
    notes: "Usa el formato separado por comas. Coordenadas invalidas pueden dejarte fuera del terreno.",
    risk: "Medio",
  }),
  game({
    command: "&notice",
    title: "Aviso del GameServer",
    category: "Comunicacion",
    syntax: "&notice <mensaje>",
    example: "&notice Redada policial inicia en 10 minutos.",
    description: "Envia un anuncio desde el GameServer a jugadores conectados.",
    notes: "Usa mensajes cortos y sin datos internos. Para anuncios globales revisa comandos @@.",
    risk: "Bajo",
  }),
  game({
    command: "&hide",
    title: "Ocultar GM",
    category: "Moderacion",
    syntax: "&hide",
    example: "&hide",
    description: "Activa modo oculto/invisible para operaciones de staff.",
    notes: "Verifica visualmente el estado antes de observar jugadores o eventos.",
    risk: "Medio",
  }),
  game({
    command: "&unhide",
    title: "Mostrar GM",
    category: "Moderacion",
    syntax: "&unhide",
    example: "&unhide",
    description: "Desactiva el modo oculto del GM.",
    notes: "Util para volver a modo visible despues de una revision o evento.",
    risk: "Bajo",
  }),
  game({
    command: "&goto",
    title: "Ir hacia un personaje",
    category: "Movimiento",
    syntax: "&goto <personaje>",
    example: "&goto Nekko",
    description: "Teletransporta al GM hacia la ubicacion del personaje indicado.",
    notes: "Para ir a coordenadas concretas utiliza &move.",
    risk: "Medio",
  }),
  game({
    command: "&kick",
    title: "Expulsar jugador",
    category: "Moderacion",
    syntax: "&kick <personaje>",
    example: "&kick BotSospechoso",
    description: "Desconecta a un jugador del servidor.",
    notes: "Documenta la razon en sanciones/logs antes o despues de usarlo.",
    risk: "Alto",
  }),
  game({
    command: "&reload",
    title: "Recargar recurso",
    category: "Servidor",
    syntax: "&reload <recurso>",
    example: "&reload lua",
    description: "Recarga scripts, tablas o recursos soportados por el GameServer.",
    notes: "Puede dejar mapas inconsistentes si se usa durante eventos o con scripts rotos.",
    risk: "Critico",
  }),
  game({
    command: "&relive",
    title: "Revivir",
    category: "Personaje",
    syntax: "&relive <personaje?>",
    example: "&relive TestPlayer",
    description: "Revive al GM o a un personaje, segun la build.",
    notes: "Usalo solo para soporte, pruebas o correccion de bugs.",
    risk: "Alto",
  }),
  game({
    command: "&qcha",
    title: "Consultar personaje",
    category: "Depuracion",
    syntax: "&qcha \"<personaje>\"",
    example: "&qcha \"Nekko\"",
    description: "Consulta informacion del personaje, incluyendo su ID interno.",
    notes: "Guarda el ID mostrado si necesitas aplicar &attr a ese personaje. Puede mostrar datos sensibles.",
    risk: "Bajo",
  }),
  game({
    command: "&qitem",
    title: "Consultar item",
    category: "Depuracion",
    syntax: "&qitem <item_id|slot>",
    example: "&qitem 1849",
    description: "Consulta informacion de item por ID o referencia de inventario.",
    notes: "Confirma IDs con ItemInfo antes de entregar o borrar objetos.",
    risk: "Bajo",
  }),
  game({
    command: "&call",
    title: "Traer personaje",
    category: "Movimiento",
    syntax: "&call <personaje>",
    example: "&call TestPlayer",
    description: "Teletransporta un personaje hacia la posicion del GM.",
    notes: "Puede interrumpir combate, comercio o eventos. Usar con criterio de staff.",
    risk: "Alto",
  }),
  game({
    command: "&gamesvrstop",
    title: "Detener GameServer",
    category: "Servidor",
    syntax: "&gamesvrstop <parametros>",
    example: "&gamesvrstop 10",
    description: "Detiene o programa parada del GameServer, segun configuracion.",
    notes: "Accion critica. Avisar, guardar estado y coordinar mantenimiento.",
    risk: "Critico",
  }),
  game({
    command: "&updateall",
    title: "Actualizar todos",
    category: "Servidor",
    syntax: "&updateall",
    example: "&updateall",
    description: "Fuerza actualizacion/sincronizacion global soportada por el GameServer.",
    notes: "No usar durante picos de jugadores sin probarlo en entorno cerrado.",
    risk: "Critico",
  }),
  game({
    command: "&harmlog=1",
    title: "Activar log de dano",
    category: "Depuracion",
    syntax: "&harmlog=1",
    example: "&harmlog=1",
    description: "Activa registro de dano/combate para diagnostico.",
    notes: "Puede generar mucho log. Activalo por periodos cortos.",
    risk: "Medio",
  }),
  game({
    command: "&harmlog=0",
    title: "Desactivar log de dano",
    category: "Depuracion",
    syntax: "&harmlog=0",
    example: "&harmlog=0",
    description: "Desactiva el registro de dano/combate.",
    notes: "Usalo al terminar la investigacion para evitar ruido en logs.",
    risk: "Bajo",
  }),
  game({
    command: "&misreload",
    title: "Recargar misiones",
    category: "Misiones",
    syntax: "&misreload",
    example: "&misreload",
    description: "Recarga definiciones o scripts de misiones.",
    notes: "Puede afectar misiones activas. Probar primero en staging.",
    risk: "Alto",
  }),
  game({
    command: "&reload_ai",
    title: "Recargar IA",
    category: "Servidor",
    syntax: "&reload_ai",
    example: "&reload_ai",
    description: "Recarga logica de IA de NPCs o monstruos.",
    notes: "Puede modificar comportamiento de mobs vivos en mapas activos.",
    risk: "Alto",
  }),
  game({
    command: "&setrecord",
    title: "Establecer record",
    category: "Depuracion",
    syntax: "&setrecord <record_id> <valor>",
    example: "&setrecord 1001 1",
    description: "Asigna un valor a un record/estado interno.",
    notes: "Puede afectar progreso persistente. Documenta cada cambio.",
    risk: "Critico",
  }),
  game({
    command: "&clearrecord",
    title: "Limpiar record",
    category: "Depuracion",
    syntax: "&clearrecord <record_id>",
    example: "&clearrecord 1001",
    description: "Borra o reinicia un record/estado interno.",
    notes: "Riesgo alto de romper progreso de personaje o mision.",
    risk: "Critico",
  }),
  game({
    command: "&setflag",
    title: "Activar flag",
    category: "Depuracion",
    syntax: "&setflag <flag_id> <valor>",
    example: "&setflag 45 1",
    description: "Establece una bandera interna de sistema/mision.",
    notes: "Las flags cambian por build y scripts. Confirmar ID antes de operar.",
    risk: "Critico",
  }),
  game({
    command: "&clearfalg",
    title: "Limpiar flag",
    category: "Depuracion",
    syntax: "&clearfalg <flag_id>",
    example: "&clearfalg 45",
    description: "Borra una bandera interna. El nombre aparece asi, con typo, en la base verificada.",
    notes: "No lo corrijas a &clearflag sin comprobar tu ejecutable.",
    risk: "Critico",
  }),
  game({
    command: "&addmission",
    title: "Agregar mision",
    category: "Misiones",
    syntax: "&addmission <mission_id>",
    example: "&addmission 2001",
    description: "Agrega/asigna una mision al contexto actual o personaje objetivo.",
    notes: "Puede saltar requisitos de historia o reputacion.",
    risk: "Alto",
  }),
  game({
    command: "&clearmission",
    title: "Limpiar mision",
    category: "Misiones",
    syntax: "&clearmission <mission_id>",
    example: "&clearmission 2001",
    description: "Limpia estado de una mision.",
    notes: "Verifica si limpia solo estado activo o tambien historial.",
    risk: "Alto",
  }),
  game({
    command: "&delmission",
    title: "Eliminar mision",
    category: "Misiones",
    syntax: "&delmission <mission_id>",
    example: "&delmission 2001",
    description: "Elimina una mision de un personaje/contexto.",
    notes: "Puede dejar recompensas o prerequisitos descuadrados.",
    risk: "Alto",
  }),
  game({
    command: "&missdk",
    title: "Depurar mision",
    category: "Misiones",
    syntax: "&missdk <mission_id|parametros>",
    example: "&missdk 2001",
    description: "Comando interno relacionado con depuracion de misiones.",
    notes: "Nombre verificado; significado exacto depende de scripts y build.",
    risk: "Alto",
  }),
  game({
    command: "&misclear",
    title: "Limpiar sistema de misiones",
    category: "Misiones",
    syntax: "&misclear <parametros>",
    example: "&misclear",
    description: "Limpieza interna relacionada con misiones.",
    notes: "Usar solo si sabes que scope limpia tu GameServer.",
    risk: "Critico",
  }),
  game({
    command: "&isblock",
    title: "Comprobar bloqueo de celda",
    category: "Depuracion",
    syntax: "&isblock <mapa?> <x> <y>",
    example: "&isblock garner 2220 2780",
    description: "Comprueba si una posicion esta bloqueada o transitable.",
    notes: "Util para QA de mapas, spawns y puntos de teletransporte.",
    risk: "Bajo",
  }),
  game({
    command: "&pet",
    title: "Gestionar mascota",
    category: "Personaje",
    syntax: "&pet <pet_id|parametros>",
    example: "&pet 101",
    description: "Comando relacionado con mascotas/fairies segun la build.",
    notes: "Puede crear estados invalidos si el pet no corresponde al personaje.",
    risk: "Alto",
  }),
  game({
    command: "&summon",
    title: "Invocar monstruo/NPC",
    category: "Spawn",
    syntax: "&summon <monster_id>",
    example: "&summon 846",
    description: "Genera una entidad por monster ID cerca del GM o punto actual.",
    notes: "Confirma el ID en MonsterInfo. Para opciones avanzadas revisa &summonex.",
    risk: "Alto",
  }),
  game({
    command: "&summonex",
    title: "Invocar avanzado",
    category: "Spawn",
    syntax: "&summonex <monster_id> <cantidad> <parametros>",
    example: "&summonex 846 1 60",
    description: "Variante avanzada de spawn con parametros adicionales.",
    notes: "Nombre verificado; revisa tu build para parametros exactos.",
    risk: "Alto",
  }),
  game({
    command: "&kill",
    title: "Matar objetivo",
    category: "Moderacion",
    syntax: "&kill <objetivo>",
    example: "&kill MobAtascado",
    description: "Mata o elimina un objetivo soportado por el GameServer.",
    notes: "Nunca usar contra jugadores sin razon documentada.",
    risk: "Alto",
  }),
  game({
    command: "&addmoney",
    title: "Agregar dinero",
    category: "Personaje",
    syntax: "&addmoney <cantidad>",
    example: "&addmoney 100000",
    description: "Agrega moneda al GM, objetivo o contexto actual segun build.",
    notes: "Impacto economico alto. Toda compensacion debe quedar auditada.",
    risk: "Critico",
  }),
  game({
    command: "&addexp",
    title: "Agregar experiencia",
    category: "Personaje",
    syntax: "&addexp <cantidad>",
    example: "&addexp 50000",
    description: "Agrega experiencia al personaje objetivo/contexto actual.",
    notes: "Puede romper progresion si supera limites o requisitos.",
    risk: "Alto",
  }),
  game({
    command: "&addlifeexp",
    title: "Agregar life exp",
    category: "Personaje",
    syntax: "&addlifeexp <cantidad>",
    example: "&addlifeexp 1000",
    description: "Agrega experiencia de vida/oficio donde el sistema exista.",
    notes: "Verifica el sistema de progresion exacto de tu servidor.",
    risk: "Alto",
  }),
  game({
    command: "&addsailexp",
    title: "Agregar sail exp",
    category: "Personaje",
    syntax: "&addsailexp <cantidad>",
    example: "&addsailexp 1000",
    description: "Agrega experiencia de navegacion.",
    notes: "Puede alterar progreso nautico o requisitos de barco.",
    risk: "Alto",
  }),
  game({
    command: "&addcess",
    title: "Agregar cess",
    category: "Personaje",
    syntax: "&addcess <cantidad>",
    example: "&addcess 10",
    description: "Modifica el valor cess asociado a progresion/sistema interno.",
    notes: "Nombre verificado; significado operativo depende de tu build.",
    risk: "Alto",
  }),
  game({
    command: "&setcesslevel",
    title: "Establecer nivel cess",
    category: "Personaje",
    syntax: "&setcesslevel <nivel>",
    example: "&setcesslevel 3",
    description: "Ajusta nivel cess en servidores que usan ese sistema.",
    notes: "Confirmar impacto antes de aplicarlo a cuentas reales.",
    risk: "Alto",
  }),
  game({
    command: "&make",
    title: "Crear item",
    category: "Inventario",
    syntax: "&make <item_id>,<cantidad>[,<gem_config>]",
    example: "&make 885,3,109",
    description: "Genera items por ID y permite configuracion adicional de gemas en builds compatibles.",
    notes: "Ejemplo simple: &make 1,1. Valida ItemInfo; gem_config depende de la build y puede crear items invalidos.",
    risk: "Critico",
  }),
  game({
    command: "&attr",
    title: "Modificar atributo",
    category: "Personaje",
    syntax: "&attr <attribute_id>,<valor>[,<character_id>]",
    example: "&attr 0,120,1503",
    description: "Cambia nivel, trabajo, puntos, stats u otros atributos por ID.",
    notes: "Obtén character_id con &qcha. No uses valores extremos; stats derivados pueden desbalancear o corromper el personaje.",
    risk: "Critico",
  }),
  game({
    command: "&itemattr",
    title: "Modificar atributo de item",
    category: "Inventario",
    syntax: "&itemattr 2,1,<pet_attribute_id>,<cantidad>",
    example: "&itemattr 2,1,26,100",
    description: "Ajusta stats del pet/fairy equipado usando IDs de atributo.",
    notes: "IDs documentados: 26 STR, 27 AGI, 28 ACC, 29 CON y 30 SPR. Valores altos pueden romper balance.",
    risk: "Critico",
  }),
  game({
    command: "&light",
    title: "Cambiar luz/estado visual",
    category: "Depuracion",
    syntax: "&light <valor>",
    example: "&light 1",
    description: "Comando relacionado con iluminacion o estado visual de mapa.",
    notes: "Nombre verificado; uso exacto depende del cliente/servidor.",
    risk: "Medio",
  }),
  game({
    command: "&seeattr",
    title: "Ver atributos",
    category: "Depuracion",
    syntax: "&seeattr <objetivo>",
    example: "&seeattr TestPlayer",
    description: "Muestra atributos de un personaje, item u objetivo.",
    notes: "Puede exponer datos internos; no compartir capturas publicas sin limpiar datos.",
    risk: "Bajo",
  }),
  game({
    command: "&forge",
    title: "Forjar item",
    category: "Inventario",
    syntax: "&forge <parametros>",
    example: "&forge 1 3",
    description: "Comando de forge/refinado de item.",
    notes: "Muy sensible para economia y balance. Usar en pruebas o eventos auditados.",
    risk: "Critico",
  }),
  game({
    command: "&skill",
    title: "Gestionar skill",
    category: "Personaje",
    syntax: "&skill <skill_id>,<nivel>",
    example: "&skill 81,1",
    description: "Otorga o ajusta skill en el contexto actual.",
    notes: "Puede dejar skills invalidas para clase/raza si se usa mal.",
    risk: "Alto",
  }),
  game({
    command: "&delitem",
    title: "Borrar item",
    category: "Inventario",
    syntax: "&delitem <item_id|slot> <cantidad>",
    example: "&delitem 1849 1",
    description: "Elimina item del inventario/contexto soportado.",
    notes: "Confirma objetivo antes de ejecutar; accion dificil de revertir sin backup.",
    risk: "Critico",
  }),
  game({
    command: "&lua",
    title: "Ejecutar Lua",
    category: "Depuracion",
    syntax: "&lua <codigo|funcion>",
    example: "&lua print('test')",
    description: "Ejecuta codigo o funcion Lua en el GameServer.",
    notes: "Extremadamente peligroso. Solo desarrolladores con entorno controlado.",
    risk: "Critico",
  }),
  game({
    command: "&lua_all",
    title: "Ejecutar Lua global",
    category: "Depuracion",
    syntax: "&lua_all <codigo|funcion>",
    example: "&lua_all print('reload check')",
    description: "Ejecuta Lua con alcance global/masivo, segun build.",
    notes: "Riesgo maximo: puede afectar todos los mapas o servidores.",
    risk: "Critico",
  }),
  game({
    command: "&setping",
    title: "Configurar ping",
    category: "Red/Grupo",
    syntax: "&setping <valor>",
    example: "&setping 150",
    description: "Configura valor o umbral relacionado con ping.",
    notes: "Puede afectar diagnostico de red o control de latencia.",
    risk: "Medio",
  }),
  game({
    command: "&getping",
    title: "Consultar ping",
    category: "Red/Grupo",
    syntax: "&getping",
    example: "&getping",
    description: "Consulta informacion de ping/latencia.",
    notes: "Util para soporte de jugadores con problemas de conexion.",
    risk: "Bajo",
  }),
  game({
    command: "&senddata",
    title: "Enviar paquete/datos",
    category: "Depuracion",
    syntax: "&senddata <payload>",
    example: "&senddata <payload_de_prueba>",
    description: "Envia datos internos soportados por el servidor.",
    notes: "Solo desarrolladores. Payloads incorrectos pueden desconectar clientes.",
    risk: "Critico",
  }),
  game({
    command: "&setpinginfo",
    title: "Configurar info de ping",
    category: "Red/Grupo",
    syntax: "&setpinginfo <parametros>",
    example: "&setpinginfo 1 150",
    description: "Ajusta informacion/diagnostico relacionado con ping.",
    notes: "Documenta valores antes de cambiarlos.",
    risk: "Medio",
  }),
  game({
    command: "&addkb",
    title: "Agregar espacios de inventario",
    category: "Personaje",
    syntax: "&addkb <cantidad>",
    example: "&addkb 48",
    description: "Agrega espacios de inventario en la sintaxis documentada por la comunidad.",
    notes: "Confirma el limite permitido por tu cliente y base de datos antes de usarlo.",
    risk: "Alto",
  }),
  game({
    command: "&itemvalid",
    title: "Validar item",
    category: "Inventario",
    syntax: "&itemvalid <item_id|slot>",
    example: "&itemvalid 6294",
    description: "Comprueba validez de item o entrada de inventario.",
    notes: "Util antes de borrar, entregar o investigar items sospechosos.",
    risk: "Bajo",
  }),
  group({
    command: "@@getlastconnection",
    title: "Ultima conexion",
    category: "Red/Grupo",
    syntax: "@@getlastconnection",
    example: "@@getlastconnection",
    description: "Consulta informacion de ultima conexion en GroupServer.",
    notes: "Puede exponer datos operativos; mantener solo para staff.",
    risk: "Bajo",
  }),
  group({
    command: "@@getuserconnection",
    title: "Conexion de usuario",
    category: "Red/Grupo",
    syntax: "@@getuserconnection <usuario>",
    example: "@@getuserconnection TestAccount",
    description: "Consulta informacion de conexion de un usuario.",
    notes: "En la base original aparece con espacio final; aqui se muestra normalizado.",
    risk: "Medio",
  }),
  group({
    command: "@@getusernum+",
    title: "Numero de usuarios",
    category: "Red/Grupo",
    syntax: "@@getusernum+",
    example: "@@getusernum+",
    description: "Consulta conteo de usuarios/conexiones.",
    notes: "Comando util para soporte y monitoreo de carga.",
    risk: "Bajo",
  }),
  group({
    command: "@@ping",
    title: "Ping de GroupServer",
    category: "Red/Grupo",
    syntax: "@@ping",
    example: "@@ping",
    description: "Prueba comunicacion o latencia del GroupServer.",
    notes: "Seguro para diagnostico basico.",
    risk: "Bajo",
  }),
  group({
    command: "@@bbs",
    title: "Mensaje BBS",
    category: "Comunicacion",
    syntax: "@@bbs <mensaje>",
    example: "@@bbs Mantenimiento en 10 minutos.",
    description: "Publica mensaje/anuncio por sistema BBS, segun configuracion.",
    notes: "Revisar alcance antes de anunciar datos sensibles.",
    risk: "Medio",
  }),
  group({
    command: "@@estop",
    title: "Parada de evento/servicio",
    category: "Servidor",
    syntax: "@@estop <objetivo>",
    example: "@@estop event_territorio",
    description: "Detiene un evento, estado o servicio soportado por GroupServer.",
    notes: "Comando critico: confirmar objetivo exacto antes de ejecutarlo.",
    risk: "Critico",
  }),
  group({
    command: "@@delestop",
    title: "Quitar parada",
    category: "Servidor",
    syntax: "@@delestop <objetivo>",
    example: "@@delestop event_territorio",
    description: "Revierte una parada establecida con estop.",
    notes: "Validar que el sistema quedo consistente despues de reactivar.",
    risk: "Alto",
  }),
  group({
    command: "@@disable",
    title: "Deshabilitar objetivo",
    category: "Servidor",
    syntax: "@@disable <objetivo>",
    example: "@@disable feature_test",
    description: "Deshabilita una funcion, objetivo o servicio segun build.",
    notes: "Nombre verificado; los objetivos validos cambian por servidor.",
    risk: "Critico",
  }),
  variant({
    command: "&help",
    title: "Ayuda de comandos",
    category: "Servidor",
    syntax: "&help",
    example: "&help",
    description: "Muestra ayuda interna si la build la conserva.",
    notes: "No aparece en la base verificada de editgmcmd; mantener como posible alias.",
    risk: "Bajo",
    prefix: "&",
  }),
  variant({
    command: "&item",
    title: "Crear item alternativo",
    category: "Inventario",
    syntax: "&item <item_id> <cantidad>",
    example: "&item 1849 10",
    description: "Alias frecuente de creacion de item en forks privados.",
    notes: "El comando verificado base es &make; usa &item solo si tu ejecutable lo trae.",
    risk: "Critico",
    prefix: "&",
  }),
  variant({
    command: "&monster",
    title: "Spawn alternativo",
    category: "Spawn",
    syntax: "&monster <monster_id> <cantidad>",
    example: "&monster 1182 1",
    description: "Alias comunitario para invocar mobs en builds modificadas.",
    notes: "El comando verificado base es &summon.",
    risk: "Alto",
    prefix: "&",
  }),
  variant({
    command: "&ban",
    title: "Bloquear cuenta/personaje",
    category: "Moderacion",
    syntax: "&ban <cuenta_o_personaje> <motivo>",
    example: "&ban BotSospechoso macro_confirmado",
    description: "Bloquea acceso en builds que lo implementan como comando GM.",
    notes: "No aparece en la base verificada; usa preferiblemente el modulo de sanciones del panel.",
    risk: "Critico",
    prefix: "&",
  }),
  variant({
    command: "&unban",
    title: "Quitar bloqueo",
    category: "Moderacion",
    syntax: "&unban <cuenta_o_personaje>",
    example: "&unban PlayerApelado",
    description: "Revierte bloqueo aplicado por un sistema compatible.",
    notes: "Debe quedar trazado en sanciones y logs.",
    risk: "Critico",
    prefix: "&",
  }),
  variant({
    command: "&mute",
    title: "Silenciar jugador",
    category: "Moderacion",
    syntax: "&mute <personaje> <minutos>",
    example: "&mute SpamUser 30",
    description: "Impide hablar a un personaje temporalmente si la build lo soporta.",
    notes: "No aparece en la base verificada; puede existir como forbidchat/disable chat en forks.",
    risk: "Medio",
    prefix: "&",
  }),
  variant({
    command: "&unmute",
    title: "Quitar silencio",
    category: "Moderacion",
    syntax: "&unmute <personaje>",
    example: "&unmute SpamUser",
    description: "Quita silencio en builds que implementan mute por comando.",
    notes: "Si no existe, manejarlo desde base de datos o modulo de sanciones.",
    risk: "Medio",
    prefix: "&",
  }),
  variant({
    command: "&level",
    title: "Cambiar nivel",
    category: "Personaje",
    syntax: "&level <personaje> <nivel>",
    example: "&level TestPlayer 45",
    description: "Ajusta nivel en builds privadas que exponen este alias.",
    notes: "En la base verificada no aparece &level; revisa si tu servidor usa &addexp.",
    risk: "Critico",
    prefix: "&",
  }),
  variant({
    command: "&speed",
    title: "Modificar velocidad GM",
    category: "Movimiento",
    syntax: "&speed <valor>",
    example: "&speed 2",
    description: "Ajusta velocidad en builds que lo incluyen.",
    notes: "No aparece en la base verificada. Vuelve siempre a velocidad normal.",
    risk: "Medio",
    prefix: "&",
  }),
  variant({
    command: "@@shutdown",
    title: "Apagado global alternativo",
    category: "Servidor",
    syntax: "@@shutdown <minutos>",
    example: "@@shutdown 10",
    description: "Nombre alternativo de apagado usado por algunas builds privadas.",
    notes: "En la base verificada aparecen @@estop/@@disable, no @@shutdown.",
    risk: "Critico",
    prefix: "@@",
  }),
];

export const gmCommandCategories = Array.from(new Set(gmCommands.map((command) => command.category)));

export const gmCommandStats = {
  total: gmCommands.length,
  verifiedGameServer: gmCommands.filter((command) => command.server === "GameServer 1.36/1.38" && command.confidence === "verificado").length,
  verifiedGroupServer: gmCommands.filter((command) => command.server === "GroupServer 1.38" && command.confidence === "verificado").length,
  variants: gmCommands.filter((command) => command.confidence === "variante").length,
};
